"""add date_posted to Post model

Revision ID: e8cc45d8e433
Revises: ea363960fab3
Create Date: 2025-03-27 19:04:02.656563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8cc45d8e433'
down_revision = 'ea363960fab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'date_posted',
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("now()")
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###
